# Generated by Django 2.2.3 on 2019-08-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinder', '0002_auto_20190814_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ingredients',
            field=models.ManyToManyField(to='recipefinder.Ingredient'),
        ),
    ]
