# Generated by Django 2.2.3 on 2019-08-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinder', '0003_cart_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(null=True),
        ),
    ]
